### ISSUE TITLE
Hang with -te option

### ISSUE THREAD

**Issue by joshuanapoli** [applitools/ImageTester#19]
I'm using ImageTester to check PDFs downloaded during a cypress test. I tried using the "-te" option to get a failing exit code from ImageTester when a discrepancy is detected. However, the process just hangs with this option.

**Comment by quinjan** [comment]
Experiencing the same issue returning this error:

`Exception in thread "main" java.lang.RuntimeException: Eyes has reported a mismatch or test failure.
This exception is thrown because the '-te' flag was present,
which instructs ImageTester to throw exceptions if a test fails, or a mismatch is detected
        at com.applitools.imagetester.lib.TestExecutor.join(TestExecutor.java:69)
        at com.applitools.imagetester.Suite.run(Suite.java:97)
        at com.applitools.imagetester.ImageTester.main(ImageTester.java:146)`

but process does not exit

Image Tester 3.5.4
